### PR TITLE
Update Packer to 1.6.6

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
https://github.com/hashicorp/packer/releases/tag/v1.6.6

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
cc @mboersma @chewong

**Comment by mboersma** [comment]
lgtm but I'd like to verify that this doesn't cause problems for aks-engine first (see Azure/aks-engine#3879 for details). I had pinned it at 1.6.1 intentionally, but I'm not positive where the problem was introduced or if 1.6.6 is ok.

**Comment by CecileRobertMichon** [comment]
I actually just realized I don't need this. The change I wanted is in 1.6.1 already https://github.com/hashicorp/packer/commit/193dad46e6d15ae4ffc49a3a176c2933419ba81c.

Feel free to close this, or we can bump the version if it doesn't break us and we want to keep it up to date.

**Comment by mboersma** [comment]
This got closed when I renamed to the "main" branch. I guess I wasn't motivated to move Packer forward if the change is already in 1.6.1, but if this would still be helpful please reopen it against `main` and I'll test it. 🙇🏼‍♂️

**Comment by CecileRobertMichon** [comment]
@mboersma, @alexeldeib opened https://github.com/hashicorp/packer/pull/10713 to fix an issue that is present in Packer 1.6.2+ so we should definitely wait until that fix is released to bump the version

**Pull request closed without merging**
