### PR TITLE
feat(Dockerfile): add ginkgo CLI to the image

### PR DESCRIPTION
**Pull request by arschles**
Partial fix for https://github.com/deis/workflow/issues/139

cc/ @krancour

### CODE REVIEW

**Comment by krancour** [comment]
I would propose tagging and releasing a 0.4.0 after this is merged.

**Comment by arschles** [comment]
@krancour wanna do the honors?

**Comment by krancour** [comment]
@arschles all set.  The 0.4.0 image is available from dockerhub and quay.io.

**Comment by arschles** [comment]
Awesome! Thanks

**Pull request merged**
