### PR TITLE
chore(rootfs/Dockerfile): update go toolchain to 1.11.4

### PR DESCRIPTION
**Pull request by mboersma**
See https://golang.org/doc/devel/release.html#go1.11.minor

### CODE REVIEW

**Comment by tariq1890** [comment]
Can we update this to `1.11.4` ? That's the latest patch release.

**Comment by mboersma** [comment]
@tariq1890 I updated it to 1.11.4. Their release notes explain why 1.11.3 was failing CI here:

> go1.11.4 (released 2018/12/14) includes fixes to cgo, the compiler, linker, runtime, documentation, go command, and the net/http and go/types packages. It includes a fix to a bug introduced in Go 1.11.3 that broke go get for import path patterns containing "...". See the [Go 1.11.4 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.11.4+label%3ACherryPickApproved) on our issue tracker for details.

**Comment by tariq1890** [comment]
@mboersma Great! Thanks for letting us know :)

**Comment by tariq1890** [comment]
I see that the diff is still showing `1.11.3`? Intentional?

**Comment by mboersma** [comment]
> Intentional?

Lol no, I'm just multitasking poorly at the end of the day. Fixed it. Thanks @tariq1890!

**Pull request merged**
